# Generated by Django 2.1.5 on 2019-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190822_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.SlugField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='realname',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='useremail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
