# Generated by Django 2.1.5 on 2019-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20190822_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.SlugField(max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='realname',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='useremail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default=3, max_length=12),
            preserve_default=False,
        ),
    ]
